# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Online Corpus
metaTitle: Online Corpus | Cyber security solutions and email protection

baseurl: "" # the subpath of the site, e.g. /blog
url: "https://onlinecorpus.com"

permalink: /:year/:month/:day/:title/

# other links
facebook_username: onlinecorpus
twitter_username: onlinecorpus
email: admin@onlinecorpus.com
linkedIn_username: online-corpus
dribbble_username:

description_footer:  Online Corpus Industries 2019&copy; All rights reserved<br> 

disqus_shortname: onlinecorpus

google_analytics_id: UA-133656432-1 

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins: [jekyll-paginate]
paginate: 6

#Social Plugin resources
social-article-url: https://onlinecorpus.com
social-article-title: Online Corpus - cyber security services, counter hacking and email protection
social-article-image: https://onlinecorpus.com/img/email-protector-banner-hackers-away.jpg
social-article-type: website