# Site
website-name: "Online Corpus"
description: "Online Corpus delivers cyber security trainings and cyber protection software that keeps criminals away from your email."
full-description: "Online Corpus is a company that helps you mitigate man in the middle and business email compromise attacks, spear phishing and whaling. We deliver cyber security trainings and cyber protection software that keeps cyber criminals away from you. The point of our website and blog is to provide you with enough knowledge, so that you will be informed about latest trends in the cyber crime world, and teach you how to stay safe."
logo: 'assets/images/logo-small.png'
favicon: 'assets/images/logo-small.png'
baseurl: 
google_analytics: 'UA-133656432-2'
disqus: 'onlinecorpus'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  georgi:
    name: Georgi Spasov
    display_name: Georgi Spasov 
    gravatar: 'assets/images/authors/georgi-spasov.jpeg'
    email: admin@onlinecorpus.com
    web: https://onlinecorpus.com
    twitter: https://twitter.com/
    description: "CEO and Webmaster of OnlineCorpus. Georgi is a digital forensics and open source expert and was the Bulgarian contact point for high-tech crimes. Currently he's devoted to code as code is devoted to him."
  ivan:
    name: Ivan K.
    display_name: Ivan K.
    gravatar: 'assets/images/authors/ivan-k.jpg'
    email: contact@onlinecorpus.com
    web: https://onlinecorpus.com
    twitter:
    description: "COO of OnlineCorpus. Ivan is a cyber security specialist and a co-author of the blog. He is an expert in the area of phishing and whaling mitigation."
       
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-7434541119036427"

#Google Analytics
analytics: "enabled"
analycis-id: "139400292"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
